### ISSUE TITLE
JS Lint your code!

### ISSUE THREAD

**Issue by phlco** [jessleenyc/simon#2]
Hiya! I just ran your code through http://www.jshint.com

It can give you some helpful warnings about things to correct

Here's the output with the line numbers and problems.  See if any of these help!

```
Five warnings
22  Missing semicolon.
32  Missing semicolon.
34  Missing semicolon.
36  Missing semicolon.
65  Expected a conditional expression and instead saw an assignment.
Three unused variables
17  randomColor
64  checkMatch
30  event
```

**Comment by jessleenyc** [comment]
Ran it through my latest JS- thanks!
